
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 25 23:21:06 CET 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 2;
  public static final int ABS = 38;
  public static final int SQR = 46;
  public static final int GE = 12;
  public static final int INPUT = 24;
  public static final int REM = 31;
  public static final int INT = 56;
  public static final int R_PAR = 52;
  public static final int TAN = 47;
  public static final int ATN = 39;
  public static final int FOR = 19;
  public static final int DATA = 15;
  public static final int LT = 10;
  public static final int FN = 48;
  public static final int RND = 43;
  public static final int SGN = 44;
  public static final int DIV = 4;
  public static final int ON = 27;
  public static final int NEXT = 26;
  public static final int IF = 23;
  public static final int EXP = 41;
  public static final int LE = 11;
  public static final int DIM = 17;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int error = 1;
  public static final int MUL = 3;
  public static final int COMA = 8;
  public static final int CHECK = 54;
  public static final int COS = 40;
  public static final int NEQ = 14;
  public static final int ERROR = 55;
  public static final int PCOMA = 9;
  public static final int LOG = 42;
  public static final int EQU = 7;
  public static final int STOP = 35;
  public static final int VAR_NUM = 49;
  public static final int RANDOMIZE = 29;
  public static final int SIN = 45;
  public static final int READ = 30;
  public static final int TO = 37;
  public static final int GOTO = 22;
  public static final int FINAL = 53;
  public static final int FLOAT = 57;
  public static final int LET = 25;
  public static final int THEN = 36;
  public static final int END = 18;
  public static final int SUM = 5;
  public static final int STRING = 58;
  public static final int L_PAR = 51;
  public static final int DEF = 16;
  public static final int RESTORE = 32;
  public static final int GT = 13;
  public static final int SUB = 6;
  public static final int GOSUB = 21;
  public static final int PRINT = 28;
  public static final int VAR_TXT = 50;
  public static final int STEP = 34;
  public static final int GO = 20;
}

